In [2]:
%load_ext autoreload
%autoreload 2

In [1]:
1+1

2

In [12]:
sentences = ["Hello world", "สวัสดีครับ"]

In [61]:
from sentence_transformers import SentenceTransformer

# Global model instance
model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2') # better model here
embeddings = model.encode(sentences)
embeddings.shape

(2, 384)

In [ ]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2') # bad
embeddings = model.encode(sentences)
embeddings.shape

(2, 384)

In [3]:
from package.intent_hub import IntentHub

query_examples = IntentHub.query()

In [47]:
embeddings = model.encode(query_examples['intent'])
embeddings

array([[-0.04159634, -0.02468182,  0.07789314, ...,  0.04773161,
        -0.00858099,  0.00637514],
       [-0.0415964 , -0.02468177,  0.07789312, ...,  0.04773157,
        -0.00858105,  0.00637514],
       [-0.04159634, -0.02468182,  0.07789314, ...,  0.04773161,
        -0.00858099,  0.00637514],
       ...,
       [-0.04159634, -0.02468182,  0.07789314, ...,  0.04773161,
        -0.00858099,  0.00637514],
       [-0.04159634, -0.02468182,  0.07789314, ...,  0.04773161,
        -0.00858099,  0.00637514],
       [-0.04159634, -0.02468182,  0.07789314, ...,  0.04773161,
        -0.00858099,  0.00637514]], shape=(50, 384), dtype=float32)

In [48]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
# from package.intents.utils import cosine_similarity

In [ ]:
np.argmax

In [ ]:
response = cosine_similarity(
    model.encode(["อยากรู้ยอดขายสองปีก่อนหน้านี้โดยแยกระหว่างชายและหญิง"]),
    model.encode(query_examples['intent'])
)
idx = np.argmax(response[0])
any(response[0]>0.6), query_examples['intent'][idx], response[0][idx],response[0]

(True,
 'ยอดขายตกช่วงไหน',
 np.float32(0.63931453),
 array([0.5679642 , 0.43887025, 0.44806677, 0.22998619, 0.45515198,
        0.19208154, 0.35559952, 0.23282209, 0.63931453, 0.22695163,
        0.3415374 , 0.3628841 , 0.23718786, 0.2113027 , 0.25113535,
        0.27452397, 0.20087652, 0.250864  , 0.13517272, 0.16905585,
        0.19959685, 0.14668676, 0.15669699, 0.14525968, 0.20928125,
        0.1643562 , 0.19745912, 0.22137439, 0.35511   , 0.357923  ,
        0.37663352, 0.2095897 , 0.18640144, 0.07704233, 0.22233588,
        0.10373239, 0.18861544, 0.00717026, 0.21408379, 0.02954501,
        0.11354268, 0.29727915, 0.04786124, 0.27431887, 0.12613532,
        0.32576108, 0.584911  , 0.21638301, 0.29732147, 0.4326824 ],
       dtype=float32))

In [79]:
response = cosine_similarity(
    model.encode(["หิวข้าวจังแต่ไม่รู้จะกินอะไรดีแนะนำหน่อยได้ไหมนะ?"]),
    model.encode(query_examples['intent'])
)
idx = np.argmax(response[0])
any(response[0]>0.6), query_examples['intent'][idx], response[0][idx],response[0]

(False,
 'เมนูไหนออเดอร์เยอะสุด',
 np.float32(0.4436605),
 array([ 1.30763948e-01,  2.26862252e-01,  8.81131142e-02,  3.28737915e-01,
         1.89798430e-01,  4.43660498e-01,  1.39459759e-01,  5.15885800e-02,
         3.84670198e-02,  1.94597304e-01,  2.23410185e-02,  7.51108825e-02,
         2.23458260e-01,  1.00398779e-01,  1.43781468e-01,  2.25807820e-03,
         1.14263603e-02, -5.19651026e-02,  3.92071754e-02, -2.12084670e-02,
         1.61689706e-04,  1.53790951e-01,  4.19136658e-02,  4.03408818e-02,
         1.16849653e-01,  5.37193194e-03,  4.46222201e-02,  1.24497630e-01,
         1.09817520e-01,  5.96751012e-02,  6.06122576e-02,  1.39007509e-01,
         4.39984649e-02, -7.42738601e-03,  1.90693736e-02,  5.23175001e-02,
         8.24738219e-02,  1.30199596e-01,  8.30458850e-03, -7.04180449e-03,
         1.17982864e-01, -2.82635912e-02, -1.95351969e-02, -1.82751417e-02,
         3.10887098e-02,  3.45807791e-01,  1.14815548e-01,  1.79904908e-01,
         8.39490443e-02,  7.96

# what if we classify intent and sendback to customer for validation in the front?

In [4]:
from package.intent_hub import IntentHub

query_examples = IntentHub.query()

In [5]:
from package.embedding.transformer_embedding import TransformerEmbedding

em = TransformerEmbedding(model_id="paraphase-embedding")

/app/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
round(float(0.00005),4)

0.0001

In [ ]:
em.run(texts=["Test"])

# What if we update idea to create graph via plotly data?

In [21]:
from package.utils import setup_logger
import logging
setup_logger(logging.DEBUG)

✅ Logging enabled (level=10) - Console


In [14]:
from pydantic import BaseModel
from typing import Any

class PlotlyData(BaseModel):
    data:Any
    layout:Any

In [41]:
from package.prompt_hub import PromptHub
from package.agents.base import Agent
from package.factory.setup_factory import setup_llms, LLMFactory

setup_llms()

agent = Agent("plotly-agent", system_prompt=PromptHub.generate_plotly_data(), DataModel=PlotlyData, format="json")
model = LLMFactory.checkout("nova-micro")
agent.model = model

In [42]:
data_str = """
{
    "index": [
      0,
      1,
      2,
      3
    ],
    "columns": [
      "sex",
      "smoker",
      "average_tip"
    ],
    "data": [
      [
        "Female",
        false,
        2.7735185185185185
      ],
      [
        "Female",
        true,
        2.931515151515151
      ],
      [
        "Male",
        false,
        3.11340206185567
      ],
      [
        "Male",
        true,
        3.0511666666666666
      ]
    ],
    "index_names": [
      null
    ],
    "column_names": [
      null
    ]
  }
}
""".strip()

# print(data_str)

In [47]:
# user_input = "I wanna know how each gender and smoker type paid for the average tips."
user_input = """\
Hey there, buddy! Let’s dive into these tip averages and see how each gender and smoking status breaks down. Here’s the lowdown on the average tips:\n\n1. **Female Non-Smokers:**\n   - Average Tip: **$2.77** \n   - Bro, these ladies who aren't smoking are tipping a bit less on average.\n\n2. **Female Smokers:**\n   - Average Tip: **$2.93**\n   - On the flip side, smoking females are tipping a bit higher, showing a slight increase of about $0.16 compared to non-smokers.\n\n3. **Male Non-Smokers:**\n   - Average Tip: **$3.11**\n   - The non-smoking dudes are tipping the highest among all groups, at an impressive average.\n\n4. **Male Smokers:**\n   - Average Tip: **$3.05**\n   - Smoking males tip slightly less than their non-smoking male buddies but still higher than female averages. \n\n### Key Patterns and Insights:\n\n- **Gender Comparison:**\n  - Generally, males tend to tip more on average than females, regardless of smoking status.\n  - Females tip $0.34 less than males on average.\n\n- **Smoking Comparison:**\n  - For females, smoking seems to increase the average tip by $0.16.\n  - For males, smoking decreases the average tip by $0.06 compared to non-smokers.\n\n### Actionable Next Steps:\n\n1. **Further Segmentation:**\n   - Consider breaking down the data by other factors like age, dining time, or type of service. This could uncover even more insights.\n   \n2. **Behavioral Analysis:**\n   - Explore if there are behavioral differences between smokers and non-smokers that could influence tipping habits. \n\n3. **Marketing Strategy:**\n   - If these trends hold up in a larger dataset, tailoring marketing strategies to each group (e.g., promotions for non-smoking females) might yield interesting results.\n\n### Follow-Up Questions:\n\n- How do these averages compare across different restaurants or dining locations?\n- Are there seasonal trends in tipping based on smoking status or gender?\n- What other demographic factors could influence tipping behavior?\n\nHope this helps you get a clearer picture, bro! If you have any more questions or need further analysis, just hit me up!
""".strip()
content = f"""\
{data_str}

{user_input}
""".strip()
response = agent.run(content)
response

ModelResponse(model_id='us.amazon.nova-micro-v1:0', role=<Role.ASSISTANT: 'assistant'>, content=PlotlyData(data=[{'x': ['Non-Smoker', 'Smoker'], 'y': [2.7735185185185185, 2.931515151515151], 'type': 'bar', 'name': 'Female', 'marker': {'color': '#1f77b4'}}, {'x': ['Non-Smoker', 'Smoker'], 'y': [3.11340206185567, 3.0511666666666666], 'type': 'bar', 'name': 'Male', 'marker': {'color': '#ff7f0e'}}], layout={'title': 'Average Tips by Gender and Smoking Status', 'xaxis': {'title': 'Smoking Status'}, 'yaxis': {'title': 'Average Tip ($)'}, 'barmode': 'group'}), reason=None, input_tokens=1446, output_tokens=468, response_time_ms=2285, id='2394e77c-1b76-46ac-9943-7fa541e0120b')

In [48]:
print(response.content)

data=[{'x': ['Non-Smoker', 'Smoker'], 'y': [2.7735185185185185, 2.931515151515151], 'type': 'bar', 'name': 'Female', 'marker': {'color': '#1f77b4'}}, {'x': ['Non-Smoker', 'Smoker'], 'y': [3.11340206185567, 3.0511666666666666], 'type': 'bar', 'name': 'Male', 'marker': {'color': '#ff7f0e'}}] layout={'title': 'Average Tips by Gender and Smoking Status', 'xaxis': {'title': 'Smoking Status'}, 'yaxis': {'title': 'Average Tip ($)'}, 'barmode': 'group'}


In [49]:
import json

with open("./test/plotly_data.json", "w") as f:
    data = response.content.model_dump()
    json.dump(data, f, indent=2)

In [ ]:
from package.llms.utils import parse_blockcode
response = model.run(system_prompt=PromptHub.generate_plotly_data(), messages=[dict(role="user", content=content)])
print(parse_blockcode(response.content, "json"))

{
  "data": [
    {
      "x": ["Female", "Male"],
      "y": [2.7735185185185185, 3.11340206185567],
      "type": "bar",
      "name": "Non-Smoker",
      "marker": {"color": "#2E86AB"}
    },
    {
      "x": ["Female", "Male"],
      "y": [2.931515151515151, 3.0511666666666666],
      "type": "bar",
      "name": "Smoker",
      "marker": {"color": "#A23B72"}
    }
  ],
  "layout": {
    "title": "Average Tips by Gender and Smoking Status",
    "xaxis": {"title": "Gender"},
    "yaxis": {"title": "Average Tip"},
    "barmode": "group"
  }
}


In [40]:
print(response.content)

```json
{
  "data": [
    {
      "x": ["Female", "Male"],
      "y": [2.7735185185185185, 3.11340206185567],
      "type": "bar",
      "name": "Non-Smoker",
      "marker": {"color": "#2E86AB"}
    },
    {
      "x": ["Female", "Male"],
      "y": [2.931515151515151, 3.0511666666666666],
      "type": "bar",
      "name": "Smoker",
      "marker": {"color": "#A23B72"}
    }
  ],
  "layout": {
    "title": "Average Tips by Gender and Smoking Status",
    "xaxis": {"title": "Gender"},
    "yaxis": {"title": "Average Tip"},
    "barmode": "group"
  }
}
```
