In [2]:
%load_ext autoreload
%autoreload 2

In [1]:
1+1

2

In [12]:
sentences = ["Hello world", "สวัสดีครับ"]

In [61]:
from sentence_transformers import SentenceTransformer

# Global model instance
model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2') # better model here
embeddings = model.encode(sentences)
embeddings.shape

(2, 384)

In [ ]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2') # bad
embeddings = model.encode(sentences)
embeddings.shape

(2, 384)

In [46]:
from package.intent_hub import IntentHub

query_examples = IntentHub.query()

In [47]:
embeddings = model.encode(query_examples['intent'])
embeddings

array([[-0.04159634, -0.02468182,  0.07789314, ...,  0.04773161,
        -0.00858099,  0.00637514],
       [-0.0415964 , -0.02468177,  0.07789312, ...,  0.04773157,
        -0.00858105,  0.00637514],
       [-0.04159634, -0.02468182,  0.07789314, ...,  0.04773161,
        -0.00858099,  0.00637514],
       ...,
       [-0.04159634, -0.02468182,  0.07789314, ...,  0.04773161,
        -0.00858099,  0.00637514],
       [-0.04159634, -0.02468182,  0.07789314, ...,  0.04773161,
        -0.00858099,  0.00637514],
       [-0.04159634, -0.02468182,  0.07789314, ...,  0.04773161,
        -0.00858099,  0.00637514]], shape=(50, 384), dtype=float32)

In [48]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
# from package.intents.utils import cosine_similarity

In [ ]:
np.argmax

In [ ]:
response = cosine_similarity(
    model.encode(["อยากรู้ยอดขายสองปีก่อนหน้านี้โดยแยกระหว่างชายและหญิง"]),
    model.encode(query_examples['intent'])
)
idx = np.argmax(response[0])
any(response[0]>0.6), query_examples['intent'][idx], response[0][idx],response[0]

(True,
 'ยอดขายตกช่วงไหน',
 np.float32(0.63931453),
 array([0.5679642 , 0.43887025, 0.44806677, 0.22998619, 0.45515198,
        0.19208154, 0.35559952, 0.23282209, 0.63931453, 0.22695163,
        0.3415374 , 0.3628841 , 0.23718786, 0.2113027 , 0.25113535,
        0.27452397, 0.20087652, 0.250864  , 0.13517272, 0.16905585,
        0.19959685, 0.14668676, 0.15669699, 0.14525968, 0.20928125,
        0.1643562 , 0.19745912, 0.22137439, 0.35511   , 0.357923  ,
        0.37663352, 0.2095897 , 0.18640144, 0.07704233, 0.22233588,
        0.10373239, 0.18861544, 0.00717026, 0.21408379, 0.02954501,
        0.11354268, 0.29727915, 0.04786124, 0.27431887, 0.12613532,
        0.32576108, 0.584911  , 0.21638301, 0.29732147, 0.4326824 ],
       dtype=float32))

In [79]:
response = cosine_similarity(
    model.encode(["หิวข้าวจังแต่ไม่รู้จะกินอะไรดีแนะนำหน่อยได้ไหมนะ?"]),
    model.encode(query_examples['intent'])
)
idx = np.argmax(response[0])
any(response[0]>0.6), query_examples['intent'][idx], response[0][idx],response[0]

(False,
 'เมนูไหนออเดอร์เยอะสุด',
 np.float32(0.4436605),
 array([ 1.30763948e-01,  2.26862252e-01,  8.81131142e-02,  3.28737915e-01,
         1.89798430e-01,  4.43660498e-01,  1.39459759e-01,  5.15885800e-02,
         3.84670198e-02,  1.94597304e-01,  2.23410185e-02,  7.51108825e-02,
         2.23458260e-01,  1.00398779e-01,  1.43781468e-01,  2.25807820e-03,
         1.14263603e-02, -5.19651026e-02,  3.92071754e-02, -2.12084670e-02,
         1.61689706e-04,  1.53790951e-01,  4.19136658e-02,  4.03408818e-02,
         1.16849653e-01,  5.37193194e-03,  4.46222201e-02,  1.24497630e-01,
         1.09817520e-01,  5.96751012e-02,  6.06122576e-02,  1.39007509e-01,
         4.39984649e-02, -7.42738601e-03,  1.90693736e-02,  5.23175001e-02,
         8.24738219e-02,  1.30199596e-01,  8.30458850e-03, -7.04180449e-03,
         1.17982864e-01, -2.82635912e-02, -1.95351969e-02, -1.82751417e-02,
         3.10887098e-02,  3.45807791e-01,  1.14815548e-01,  1.79904908e-01,
         8.39490443e-02,  7.96

# what if we classify intent and sendback to customer for validation in the front?